name: Yumemi
services:
  - load: discord
    jobs:
      - load: discourse
        url: https://forum.kazamatsuri.org
      - load: verification
        channel: {{ 'test' if grains.get('vagrant') else 'access-requests' }}
        grant: Member
        discourse:
          url: https://forum.kazamatsuri.org
          topic_id: 2000
          trust_level: 2
        lines:
          success: "Your identity has been verified, welcome!"
          name_not_in_post: "Hm, it doesn't appear as though you have mentioned your Discord username in your forum post... perhaps you did not spell it correctly?"
          level_too_low: "I'm sorry, but I cannot let you in until you have reached the 'Member' trust level. To raise your trust level, please participate on the forum for a few days, and it should come naturally. You may confirm your trust level on your forum user page at any time."
          error: "I apologize, but I am unable to verify you... there appears to be something wrong... um, please try again!"
      - load: conversion
        lines:
          currency: "%s would be... %s. Do note that my sources only update once per day, so this may be a little bit old."
          currency_multi: "%s would be $%s, €%s, £%s or ¥%s. Do note that my sources only update once per day, so this may be a little bit old."
  # - load: discourse
  #   url: https://forum.kazamatsuri.org
