HTTP/1.0 {% block code %}{% endblock %}
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
  <body>
    <h1>{% block title %}OVERRIDE TITLE BLOCK PLS{% endblock %}</h1>
    {% block content %}OVERRIDE CONTENT BLOCK PLS{% endblock %}
  </body>
</html>
